name: Run Report (Windows)

on:
  workflow_dispatch:
    inputs:
      report:
        description: 'Jelentés (1/2/3)'
        default: '3'
        required: false
      csv_url:
        description: 'MASTER CSV URL (üres = DEFAULT_CSV_URL)'
        default: ''
        required: false
  repository_dispatch:
    types: [run_report]

jobs:
  run:
    runs-on: windows-latest
    env:
      # <<< IDE írd, ha másik publikus CSV-t akarsz alapértelmezettnek >>>
      DEFAULT_CSV_URL: https://docs.google.com/spreadsheets/d/e/2PACX-1vTf5h3xx4LWJvI-e7PSyc8g6uGZT-H6pCeuwEqs7NqeCDKuAltTpL_ncPOWMtooRw/pub?output=csv

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests yfinance pytz

      - name: Resolve inputs (report, csv)
        id: vars
        shell: pwsh
        run: |
          $report = "${{ github.event.inputs.report }}"
          if (-not $report) { $report = "${{ github.event.client_payload.report }}" }
          if (-not $report) { $report = "3" }

          $csv = "${{ github.event.inputs.csv_url }}"
          if (-not $csv) { $csv = "${{ github.event.client_payload.csv_url }}" }
          if (-not $csv) { $csv = "${{ env.DEFAULT_CSV_URL }}" }

          "report=$report" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "csv=$csv"       | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          Write-Host "REPORT: $report"
          Write-Host "CSV URL: $csv"

      - name: Fetch MASTER CSV + preview (robust)
        shell: pwsh
        run: |
          $csvUrl = "${{ steps.vars.outputs.csv }}"
          if (-not $csvUrl) { Write-Error "Hiányzik a CSV URL."; exit 1 }
          New-Item -ItemType Directory -Force -Path reports | Out-Null
          $out = "reports\master.csv"

          Write-Host "Letöltés: $csvUrl"
          & curl.exe -fL --retry 3 --retry-all-errors -A "Mozilla/5.0" "$csvUrl" -o "$out"
          if ($LASTEXITCODE -ne 0) { Write-Error "CSV letöltés sikertelen (curl exit $LASTEXITCODE)."; exit 1 }

          if ((Get-Item "$out").Length -lt 10) { Write-Error "A CSV túl kicsi / üres."; exit 1 }
          $first = Get-Content "$out" -TotalCount 1
          if ($first -match "<!DOCTYPE html>|<html") { Write-Error "Nem CSV érkezett (HTML). Ellenőrizd a linket/megosztást."; exit 1 }

          Write-Host "Első 5 sor:"
          Get-Content "$out" -TotalCount 5 | ForEach-Object { Write-Host "CSV> $_" }

      - name: Run report (#3 + extrém override)
        shell: pwsh
        run: |
          # Konzol + Python kimenet legyen UTF-8 (nyilak, ékezetek)
          [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
          $env:PYTHONIOENCODING = "utf-8"

          $report = "${{ steps.vars.outputs.report }}"
          $csv    = "reports\master.csv"
          if (-not (Test-Path "scripts\report_runner.py")) {
            Write-Error "scripts\report_runner.py hiányzik. Másold be a repo-ba a mellékelt fájlt."
            exit 1
          }
          python -X utf8 "scripts\report_runner.py" --report $report --csv "$csv" --summary "$env:GITHUB_STEP_SUMMARY"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: report-bundle
          path: reports/**
          if-no-files-found: warn
