name: Run Report

on:
  # kézi indítás GitHub UI-ból vagy API-ból
  workflow_dispatch:
    inputs:
      report:
        description: "1 = AH+PM | 2 = Open→Close | 3 = Open→Most"
        required: true
        default: "1"
  # telefon/iOS/Windows API hívás (repository_dispatch) támogatása is
  repository_dispatch:
    types: [run_report]

permissions:
  contents: write    # hogy a reports/ mappába tudjunk commitolni
  actions: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests pandas python-dateutil feedparser yfinance
          fi

      - name: Resolve REPORT arg
        id: rep
        shell: bash
        run: |
          # workflow_dispatch → github.event.inputs.report
          # repository_dispatch → github.event.client_payload.report
          REP="${{ github.event.inputs.report }}"
          [ -z "$REP" ] && REP="${{ github.event.client_payload.report }}"
          [ -z "$REP" ] && REP="1"
          echo "report=$REP" >> $GITHUB_OUTPUT

      - name: Run report
        run: |
          mkdir -p reports
          python scripts/report_runner.py --report "${{ steps.rep.outputs.report }}"

      - name: Auto-commit reports/
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: update reports (report ${{ steps.rep.outputs.report }})"
          file_pattern: reports/*.json

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ steps.rep.outputs.report }}
          path: reports/*.json
          if-no-files-found: warn
