name: Run Report

# Csak kézi indítás (Actions > Run workflow)
on:
  workflow_dispatch:
    inputs:
      report:
        description: "Melyik jelentés? (1, 2 vagy 3)"
        required: true
        default: "1"

# A repo-ba pusholunk, ehhez kell write jogosultság
permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found — skipping."
          fi

      - name: Run report
        env:
          REPORT: ${{ github.event.inputs.report }}
          CSV_URL: ${{ secrets.MASTER_CSV_URL }}
        run: python scripts/report_runner.py --report "$REPORT" --csv-url "$CSV_URL"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ github.run_number }}
          path: out/**
          if-no-files-found: warn
          retention-days: 7

      - name: Commit reports into repo
        env:
          REPORT: ${{ github.event.inputs.report }}
        run: |
          set -e
          REPORT_DIR="reports/${REPORT}"
          mkdir -p "$REPORT_DIR"
          cp -r out/* "$REPORT_DIR/"

          # Stabil "latest" alias a gyors lekéréshez
          cp out/report_summary.md "reports/latest_${REPORT}.md"
          cp out/report.json        "reports/latest_${REPORT}.json"

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add reports/
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "report ${REPORT} #${{ github.run_number }}"
            git push
          fi
